spring:
  application:
    name: membership
  main:
    banner-mode: "off"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    jdbcUrl: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:foobar}